// src/animations.ts — GENERATED BY NOVA. Do not hand-edit.
// Motion for this build, seeded on the brand — the export names are fixed and
// every component imports them by hand; only the values below vary.
import type { Variants, Transition } from "framer-motion";

// === SPRING CONFIGS ===
export const spring = {
  gentle: { type: "spring", stiffness: 115, damping: 19 } as Transition,
  snappy: { type: "spring", stiffness: 249, damping: 21 } as Transition,
  bouncy: { type: "spring", stiffness: 387, damping: 9 } as Transition,
  slow: { type: "spring", stiffness: 65, damping: 22 } as Transition,
};

// === EASING ===
export const ease = {
  smooth: [0.33, 1, 0.68, 1] as const,
  snappy: [0.16, 1, 0.3, 1] as const,
  cinematic: [0.76, 0, 0.24, 1] as const,
};

// === DIRECTIONAL FADES ===
export const fadeUp: Variants = {
  hidden: { opacity: 0, y: 38 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: ease.smooth } },
};
export const fadeDown: Variants = {
  hidden: { opacity: 0, y: -30 },
  show: { opacity: 1, y: 0, transition: { duration: 0.46, ease: ease.smooth } },
};
export const fadeLeft: Variants = {
  hidden: { opacity: 0, x: -46 },
  show: { opacity: 1, x: 0, transition: { duration: 0.68, ease: ease.smooth } },
};
export const fadeRight: Variants = {
  hidden: { opacity: 0, x: 49 },
  show: { opacity: 1, x: 0, transition: { duration: 0.5, ease: ease.smooth } },
};
export const scaleIn: Variants = {
  hidden: { opacity: 0, scale: 0.86 },
  show: { opacity: 1, scale: 1, transition: spring.gentle },
};

// === STAGGER FACTORY ===
export const stagger = (
  delayChildren = 0.08,
  staggerChildren = 0.08,
): Variants => ({
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { delayChildren, staggerChildren } },
});

// === HERO SECTION ===
export const heroContainer: Variants = {
  hidden: {},
  show: { transition: { staggerChildren: 0.15, delayChildren: 0.2 } },
};
export const heroItem: Variants = {
  hidden: { opacity: 0, y: 64, filter: "blur(8px)" },
  show: {
    opacity: 1,
    y: 0,
    filter: "blur(0px)",
    transition: { duration: 0.9, ease: ease.smooth },
  },
};

// === PAGE TRANSITIONS ===
export const pageTransition: Variants = {
  initial: { opacity: 0, y: 14 },
  animate: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.47, ease: ease.smooth },
  },
  exit: {
    opacity: 0,
    y: -9,
    transition: { duration: 0.24, ease: ease.cinematic },
  },
};

// === HOVER PRESETS ===
export const hoverLift = { y: -5, transition: spring.snappy };
export const hoverScale = { scale: 1.04, transition: spring.snappy };
export const hoverGlow = {
  boxShadow: "0 25px 39px rgba(0,0,0,0.12)",
  transition: { duration: 0.3 },
};

// === ALIASES FOR NAMES MODELS INVENT ===
// Not part of the system — see `_ANIMATION_ALIASES`. A component importing
// `fadeInUp` fails to resolve the module and takes the page down with it, so
// these cost four lines and remove a build failure.
export const fadeInUp = fadeUp;
export const fadeInDown = fadeDown;
export const fadeInLeft = fadeLeft;
export const fadeInRight = fadeRight;
